=== LXLLXVX/LND/ACTIVIDAD 4/ACTIVIDAD4.dtd
<!ELEMENT pedidos (pedido, datos)>
<!ELEMENT pedido (pizzas)>
<!ELEMENT pizzas (pizza*)>
<!ELEMENT pizza (tipo, cantidad, extras)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT extras (extra?)>
<!ELEMENT extra (#PCDATA)>

<!ELEMENT datos (nombre_destinatario, direccion)>
<!ELEMENT nombre_destinatario (#PCDATA)>
<!ELEMENT direccion (calle, numero)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>

=== LXLLXVX/LND/ACTIVIDAD 4/ACTIVIDAD4.xml
<?xml version="1.0"?>
<!DOCTYPE pedidos SYSTEM "ACTIVIDAD4.dtd">

<pedidos>
    <pedido>
        <pizzas>
            <pizza>
                <tipo> Margarita </tipo>
                <cantidad> 1 </cantidad>
                <extras>
                    <extra>pimientos morrones</extra>
                </extras>
            </pizza>

            <pizza>
                <tipo> Artesana </tipo>
                <cantidad> 2 </cantidad>
                <extras>
                    <extra></extra>
                </extras>
            </pizza>
            
            <pizza>
                <tipo> Vegetal </tipo>
                <cantidad> 1 </cantidad>
                <extras>
                    <extra></extra>
                </extras>
            </pizza>
        </pizzas>
    </pedido>

    <datos>
        <nombre_destinatario> Pepe PÃ©rez </nombre_destinatario>
        <direccion>
            <calle> Guanarteme </calle>
            <numero> 17 </numero>
        </direccion>
    </datos>
    
</pedidos>
