=== LXLLXVX/LND/ACTIVIDAD 1/ACTIVIDAD1.dtd
<!ELEMENT alumno (nombre,apellidos,modulos,direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (#PCDATA)>
<!ELEMENT direccion (calle,numero)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>

=== LXLLXVX/LND/ACTIVIDAD 1/ACTIVIDAD1.xml
<?xml version="1.0"?>
<!DOCTYPE alumno SYSTEM "ACTIVIDAD1.dtd">

<alumno>

    <nombre>√Ångel</nombre>
    <apellidos>Lallave Herrera</apellidos>

    <modulos>
        <modulo>LND</modulo>
        <modulo>FOL</modulo>
        <modulo>sjdas</modulo>
    </modulos>

    <direccion>
        <calle>Guanarteme</calle>
        <numero>7</numero>
    </direccion>

</alumno>
